name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        browser: [chromium, firefox]
        shard: [1,2,3,4,5,6,7,8,9,10]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Playwright browsers
        run: |
          python -m playwright install
      - name: Run tests
        env:
          PLAYWRIGHT_BROWSER: ${{ matrix.browser }}
          PYTEST_SHARD: ${{ matrix.shard }}
          PYTEST_NUM_SHARDS: 10
        run: |
          # You could shard tests here; currently it runs all tests on each shard.
          pytest -n auto --maxfail=1 --alluredir=allure-results
      - name: Upload Allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results-${{ matrix.os }}-${{ matrix.browser }}-${{ matrix.shard }}
          path: allure-results